class GenericServlet:  #builtin class
    def m1(self):
        .........
        .........
        .........

class myservlet(GenericServlet):
    super().m1()
    ..........
    .......... here executing pre-defined  +
    .......... and also executing userdefined logic
